---------------------------

CREATE TABLE employees
  (
    employee_id NUMBER 
                GENERATED BY DEFAULT AS IDENTITY START WITH 108 
                PRIMARY KEY,
    first_name VARCHAR( 255 ) NOT NULL,
    last_name  VARCHAR( 255 ) NOT NULL,
    username      VARCHAR( 255 ) NOT NULL,
    pass     VARCHAR( 50 ) NOT NULL ,
  );
